name: Build Launcher

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload HTA
        uses: actions/upload-artifact@v4
        with:
          name: GrifLauncher
          path: launcher.hta
